#!/usr/bin/env python3
"""
Plot PLL LVS netlist transient simulation results.
Reads lvs_pll_sim.tsv generated by ngspice.
"""

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJ_DIR = os.path.dirname(SCRIPT_DIR)
TSV_FILE = os.path.join(PROJ_DIR, "sim", "results", "lvs_pll_sim.tsv")
OUT_DIR = os.path.join(PROJ_DIR, "sim", "results")


def load_tsv(path):
    """Load ngspice paired-column output: (time, v(sig)) repeated per signal."""
    with open(path) as f:
        header = f.readline().strip().split()
    signal_names = []
    for i in range(1, len(header), 2):
        signal_names.append(header[i].strip())
    data = np.loadtxt(path, skiprows=1)
    signals = {}
    for i, name in enumerate(signal_names):
        t_col = i * 2
        v_col = i * 2 + 1
        signals[name] = (data[:, t_col], data[:, v_col])
    return signals


def plot_vctrl_settling(signals):
    t, v = signals['v(XPLL.vctrl)']
    fig, ax = plt.subplots(figsize=(10, 4))
    ax.plot(t * 1e6, v, color='steelblue', linewidth=0.8)
    ax.set_xlabel('Time (µs)')
    ax.set_ylabel('Vctrl (V)')
    ax.set_title('LVS PLL — Control Voltage Settling')
    ax.set_xlim(0, t[-1] * 1e6)
    ax.set_ylim(0, 1.2)
    ax.grid(True, linestyle=':', linewidth=0.5)
    fig.tight_layout()
    path = os.path.join(OUT_DIR, 'lvs_vctrl_settling.png')
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"  Saved: {path}")


def plot_waveforms_end(signals):
    """Plot ref_clk, div_clk, vco_out at end of simulation."""
    t_ref, v_ref = signals['v(ref_clk)']
    t_div, v_div = signals['v(XPLL.div_clk)']
    t_vco, v_vco = signals['v(XPLL.vco_out)']

    t_end = t_ref[-1]
    t_start = t_end - 100e-9

    fig, axes = plt.subplots(3, 1, figsize=(10, 7), sharex=True)

    mask = t_ref >= t_start
    axes[0].plot(t_ref[mask] * 1e9, v_ref[mask], color='#2196F3', linewidth=1)
    axes[0].set_ylabel('ref_clk (V)')
    axes[0].set_title(f'LVS PLL Waveforms (last 100 ns, t={t_end*1e6:.1f} µs)')
    axes[0].set_ylim(-0.1, 1.9)
    axes[0].grid(True, linestyle=':', linewidth=0.5)

    mask = t_div >= t_start
    axes[1].plot(t_div[mask] * 1e9, v_div[mask], color='#4CAF50', linewidth=1)
    axes[1].set_ylabel('div_clk (V)')
    axes[1].set_ylim(-0.1, 1.9)
    axes[1].grid(True, linestyle=':', linewidth=0.5)

    mask = t_vco >= t_start
    axes[2].plot(t_vco[mask] * 1e9, v_vco[mask], color='#FF5722', linewidth=1)
    axes[2].set_ylabel('vco_out (V)')
    axes[2].set_xlabel('Time (ns)')
    axes[2].set_ylim(-0.1, 1.9)
    axes[2].grid(True, linestyle=':', linewidth=0.5)

    fig.tight_layout()
    path = os.path.join(OUT_DIR, 'lvs_waveforms_end.png')
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"  Saved: {path}")


def plot_up_dn(signals):
    t_up, v_up = signals['v(XPLL.up)']
    t_dn, v_dn = signals['v(XPLL.dn)']

    # Show 500ns window around 10µs
    t0, t1 = 9.5e-6, 10.0e-6
    fig, axes = plt.subplots(2, 1, figsize=(10, 4), sharex=True)

    mask = (t_up >= t0) & (t_up <= t1)
    axes[0].plot(t_up[mask] * 1e9, v_up[mask], color='#E91E63', linewidth=1)
    axes[0].set_ylabel('UP (V)')
    axes[0].set_title('PFD UP/DN (9.5–10.0 µs)')
    axes[0].set_ylim(-0.1, 1.9)
    axes[0].grid(True, linestyle=':', linewidth=0.5)

    mask = (t_dn >= t0) & (t_dn <= t1)
    axes[1].plot(t_dn[mask] * 1e9, v_dn[mask], color='#9C27B0', linewidth=1)
    axes[1].set_ylabel('DN (V)')
    axes[1].set_xlabel('Time (ns)')
    axes[1].set_ylim(-0.1, 1.9)
    axes[1].grid(True, linestyle=':', linewidth=0.5)

    fig.tight_layout()
    path = os.path.join(OUT_DIR, 'lvs_up_dn_pulses.png')
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"  Saved: {path}")


def plot_vco_frequency(signals):
    t, v = signals['v(XPLL.vco_out)']
    threshold = 0.9
    crossings = []
    for i in range(1, len(v)):
        if v[i-1] < threshold <= v[i]:
            frac = (threshold - v[i-1]) / (v[i] - v[i-1])
            tc = t[i-1] + frac * (t[i] - t[i-1])
            crossings.append(tc)
    crossings = np.array(crossings)

    if len(crossings) < 3:
        print("  Not enough VCO crossings for frequency plot")
        return

    periods = np.diff(crossings)
    freq = 1.0 / periods / 1e6  # MHz
    t_mid = (crossings[:-1] + crossings[1:]) / 2

    fig, ax = plt.subplots(figsize=(10, 4))
    ax.plot(t_mid * 1e6, freq, color='#FF9800', linewidth=0.5, alpha=0.7)
    ax.axhline(400, color='tomato', linestyle='--', linewidth=0.8, label='Target: 400 MHz')
    ax.set_xlabel('Time (µs)')
    ax.set_ylabel('VCO Frequency (MHz)')
    ax.set_title('LVS PLL — Instantaneous VCO Frequency')
    ax.set_xlim(0, t[-1] * 1e6)
    ax.set_ylim(100, 800)
    ax.legend()
    ax.grid(True, linestyle=':', linewidth=0.5)
    fig.tight_layout()
    path = os.path.join(OUT_DIR, 'lvs_vco_frequency.png')
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"  Saved: {path}")


def main():
    print(f"LVS PLL Simulation Plots")
    print(f"  Input: {TSV_FILE}")
    if not os.path.exists(TSV_FILE):
        print("ERROR: TSV file not found. Run ngspice simulation first.")
        return
    signals = load_tsv(TSV_FILE)
    print(f"  Loaded {len(signals)} signals, {len(list(signals.values())[0][0])} samples")
    print()
    plot_vctrl_settling(signals)
    plot_waveforms_end(signals)
    plot_up_dn(signals)
    plot_vco_frequency(signals)
    print("\nDone.")


if __name__ == "__main__":
    main()
